version: 2

updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    insecure-external-code-execution: allow
    versioning-strategy: auto
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    groups:
      sorbet:
        patterns:
          - "sorbet*"
          - "tapioca"
          - "rbi"
          - "spoom"
      patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "rails"
          - "sorbet*"
          - "tapioca"
          - "rbi"
          - "spoom"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
